apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      name: proxy
    - port: 443
      targetPort: 8443
      name: proxy-ssl
  selector:
    app: kong
